bind = "0.0.0.0:5000"
workers = 3  # 仮想3コアに合わせて調整
threads = 2
worker_class = "gevent"  # 非同期I/Oに対応
timeout = 60
keepalive = 5
loglevel = "info"  # デバッグから情報レベルに変更
accesslog = "-"
errorlog = "-"
max_requests = 1000
max_requests_jitter = 50
capture_output = True